version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name:  elasticsearch
    environment: 
      - discovery.type=single-node
      - cluster.name=es-docker-sn-cluster
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data:/usr/share/elasticsearch/data 
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge